---
# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: ccm-monitoring

---
# Loki ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: ccm-monitoring
data:
  loki.yaml: |
    auth_enabled: false
    
    server:
      http_listen_port: 3100
      grpc_listen_port: 9096
    
    common:
      path_prefix: /tmp/loki
      storage:
        filesystem:
          chunks_directory: /tmp/loki/chunks
          rules_directory: /tmp/loki/rules
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory
    
    schema_config:
      configs:
        - from: 2024-01-01
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h
    
    ruler:
      enable_api: true
      enable_alertmanager_v2: true
      storage:
        type: local
        local:
          directory: /tmp/loki/rules
    
    analytics:
      reporting_enabled: false

---
# Loki StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki
  namespace: ccm-monitoring
spec:
  serviceName: loki
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      initContainers:
      - name: init-loki
        image: busybox:1.35
        command:
        - sh
        - -c
        - |
          mkdir -p /tmp/loki/chunks /tmp/loki/rules
          chmod -R 777 /tmp/loki
        volumeMounts:
        - name: storage
          mountPath: /tmp/loki
      containers:
      - name: loki
        image: grafana/loki:3.0.0
        args:
          - -config.file=/etc/loki/loki.yaml
        ports:
        - containerPort: 3100
          name: http
        - containerPort: 9096
          name: grpc
        volumeMounts:
        - name: config
          mountPath: /etc/loki
        - name: storage
          mountPath: /tmp/loki
        - name: rules
          mountPath: /tmp/loki/rules-config
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1Gi
      volumes:
      - name: config
        configMap:
          name: loki-config
      - name: rules
        configMap:
          name: loki-rules
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi

---
# Loki Internal Service
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: ccm-monitoring
spec:
  type: ClusterIP
  ports:
  - port: 3100
    targetPort: 3100
    protocol: TCP
    name: http
  - port: 9096
    targetPort: 9096
    protocol: TCP
    name: grpc
  selector:
    app: loki

---
# Loki External LoadBalancer (restricted access)
apiVersion: v1
kind: Service
metadata:
  name: loki-external
  namespace: ccm-monitoring
  annotations:
    networking.gke.io/load-balancer-source-ranges: "88.171.246.28/32,10.0.0.0/24,10.4.0.0/14,10.8.0.0/20,78.241.105.69/32"
spec:
  type: LoadBalancer
  ports:
  - port: 3100
    targetPort: 3100
    protocol: TCP
  selector:
    app: loki

---
# Grafana ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: ccm-monitoring
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki:3100
      isDefault: true

---
# Grafana Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: ccm-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      initContainers:
      - name: init-grafana
        image: busybox:1.35
        command:
        - sh
        - -c
        - |
          mkdir -p /var/lib/grafana/plugins /var/lib/grafana/dashboards /var/lib/grafana/alerting
          chmod -R 777 /var/lib/grafana
          chown -R 472:472 /var/lib/grafana
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
      containers:
      - name: grafana
        image: grafana/grafana:10.4.0
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "admin123"
        - name: GF_INSTALL_PLUGINS
          value: ""
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
      volumes:
      - name: grafana-storage
        persistentVolumeClaim:
          claimName: grafana-pvc
      - name: grafana-datasources
        configMap:
          name: grafana-datasources

---
# Grafana PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: ccm-monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
# Grafana Internal Service
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: ccm-monitoring
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: grafana

---
# Grafana External LoadBalancer
apiVersion: v1
kind: Service
metadata:
  name: grafana-external
  namespace: ccm-monitoring
  annotations:
    networking.gke.io/load-balancer-source-ranges: "88.171.246.28/32,10.0.0.0/24,10.4.0.0/14,10.8.0.0/20,78.241.105.69/32"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: grafana

---
# Loki Alert Rules ConfigMap (optional)
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-rules
  namespace: ccm-monitoring
data:
  rules.yaml: |
    groups:
      - name: error_alerts
        interval: 1m
        rules:
          - alert: HighErrorRate
            expr: |
              sum(rate({namespace="monitoring"} |= "error" [5m])) > 10
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: "High error rate detected"
              description: "Error rate is above 10 errors per second"